
version: "3.9"
services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        environment:
            MONGODB_DATABASE: dataviz
        ports:
            - "27017:27017"
        restart: always
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        environment:
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_MONGODB_PORT: 27017
        ports:
            - "8081:8081"
        restart: always
